version: '3.8'

services:
  backend:
    build: ./backend/
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  frontend:
    build: ./frontend/
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data_prod: